baseURL = 'https://dredd-13.github.io/'
locale = 'es-ES'
title = 'Dredd'
theme = "PaperMod"

[params]
  hideFooter = true
  defaultTheme = "dark"
  ShowToc = true
  TocOpen= true

 [params.maintenance]
    enabled = false           # true = TODO el sitio en mantenimiento
    sections = []            # Secciones específicas: ["posts", "certs", "ctfs"]

[markup.highlight]
  style = "dracula"