baseURL = 'https://dredd-13.github.io/'
locale = 'es-ES'
title = 'Dredd'
theme = "PaperMod"

[params]
  hideFooter = true
  defaultTheme = "dark"

[[menus.main]]
  name = "Whoami"
  url = "/whoami"
  weight = 1